name: Build and Push to HF Spaces
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to HuggingFace
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo $HF_TOKEN | docker login hf.co -u zhepama --password-stdin

      - name: Build and push Docker image
        env:
          IMAGE_NAME: hf.co/zhepama/hf-hono
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
