name: Build and Push to HF Spaces
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to HuggingFace
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo $HF_TOKEN | docker login registry.hf.space -u zhepama --password-stdin

      - name: Build and push Docker image
        env:
          IMAGE_NAME: registry.hf.space/zhepama/hf-hono
        run: |
          docker build -t registry.hf.space/zhepama/hf-hono:latest .
          docker push registry.hf.space/zhepama/hf-hono:latest
